### ISSUE TITLE
`index.json` seems to be missing

### ISSUE THREAD

**Issue by johndatserakis** [words/profanities#18]
I might be missing something, but `index.json` doesn't seem to be in the source files. Thank you.

**Comment by wooorm** [comment]
Whoops you’re right, [it’s generated](https://github.com/words/profanities/blob/464a440cc1d6a8c1f604fd8c0e11f4722dfa3193/script/build-data.js).

Did you run into the readme linking to it? If so, I’d love a PR fixing it!

**Comment by johndatserakis** [comment]
Ok if I can carve out some time I'll look at this

**Comment by Murderlon** [comment]
`index.json` has been in `.gitignore` for two years: https://github.com/words/profanities/commit/a142e48528301bf10713069f0c6126d2c12e57da. @wooorm I'm guessing you no longer want to ignore it since the other languages were added?

**Comment by wooorm** [comment]
Difference is that our English list Mostly an online resource, crawled into this package, so it doesn't need to be in source control, whereas the others are!

I did recently think about instead crawling this project from cuss, as it has more information and it's hard to keep in sync, but that would mean all files are outside of source control!

**Comment by Murderlon** [comment]
It would be interesting as currently the two always have to be manually in sync (e.g https://github.com/words/profanities/commit/953b39a2dfe584e4d2abe5f5c9ca16add6d90182 with https://github.com/words/cuss/commit/e3c0e699bc7cb9454f02799217513f1f55817baf), which seems superfluous. But then again, the single purpose of this lib is its data, not data fetchers and right now there are lots of dependencies for just that.

Either way would be nice to choose a single approach?

**Comment by johndatserakis** [comment]
Hey I'm sorry I caused a ruckus by making this issue - I'm a bit confused with the layout here and not sure if I can be helpful. 

I was simply looking for a .json file with a list of profanities. I liked `cuss` but I wanted just the word list. I see that when I `npm install profanities` the resulting `node_modules` `profanities` folder has an `index.json` file in it - so that's enough for me - but perhaps there is more here like what you guys are discussing. Thanks.

**Comment by Murderlon** [comment]
No worries! If anything it's good that issues cause debate for improvements. 

But now that you mention it, I forgot for a sec that when you `require`/`import` it it doesn't really matter whether the data was locally there or (partially) from an external source, it will just be there. So in that case @wooorm I think crawling from cuss would be an improvement.

**Comment by wooorm** [comment]
Yeah don’t worry about this sparking a conversation @johndatserakis!
I’m going to remove all JSON files from this repo in GH-19, so I’m going to close this issue, as that, uhmm, solves the missing index.json haha :p
